// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCjrjJMmP7K8JtDewmIPCW--2OALrT5KpQ',
    appId: '1:673130041200:web:4b478d38b6329aab7cc9b5',
    messagingSenderId: '673130041200',
    projectId: 'connectycube-38b82',
    authDomain: 'connectycube-38b82.firebaseapp.com',
    storageBucket: 'connectycube-38b82.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBLfXmbyj-exVBIqN2c0RYhjVSh6HxvVfk',
    appId: '1:673130041200:android:b328eb2741be61257cc9b5',
    messagingSenderId: '673130041200',
    projectId: 'connectycube-38b82',
    storageBucket: 'connectycube-38b82.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBUjuXxo2yC-iUkke9weqIEdxvR2zp7lRw',
    appId: '1:673130041200:ios:618f81461347351e7cc9b5',
    messagingSenderId: '673130041200',
    projectId: 'connectycube-38b82',
    storageBucket: 'connectycube-38b82.firebasestorage.app',
    iosBundleId: 'com.connectycube.flutter.p2p-call-sample.app.val',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBUjuXxo2yC-iUkke9weqIEdxvR2zp7lRw',
    appId: '1:673130041200:ios:bdd53668299d63a27cc9b5',
    messagingSenderId: '673130041200',
    projectId: 'connectycube-38b82',
    storageBucket: 'connectycube-38b82.firebasestorage.app',
    iosBundleId: 'com.connectycube.flutter.p2p-call-sample.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCjrjJMmP7K8JtDewmIPCW--2OALrT5KpQ',
    appId: '1:673130041200:web:7460e93c4ea061387cc9b5',
    messagingSenderId: '673130041200',
    projectId: 'connectycube-38b82',
    authDomain: 'connectycube-38b82.firebaseapp.com',
    storageBucket: 'connectycube-38b82.firebasestorage.app',
  );

}